name = "llm"
main = "packages/server/src/index.ts"
compatibility_date = "2025-06-01"
keep_vars = true
routes = [ { pattern = "llm.rettend.me", custom_domain = true } ]

[[kv_namespaces]]
binding = "REGISTRY"
id = "623d8b76dab74f37b63d66cbe55588c4"

[triggers]
crons = [ "0 2 * * *" ]
